#端口，项目上下文根
server:
  port: 8080
#  servlet:
#    context-path: /hotel
spring:
#  profiles:
#    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  #数据库相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.cui.pojo.entity          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件

############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
#mapper:
#  mappers: com.cui.pojo.mapper
#  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
#  identity: MYSQL

#  # 开发环境配置
#  profiles: dev
#
#  resources:
#    #指定静态资源路径，默认为classpath:[/META-INF/resources/,/resources/, /static/, /public/]以及context:/
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/}
#